# Generated by Django 3.2.6 on 2021-08-31 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specified', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(upload_to='profile_image')),
                ('fb_link', models.CharField(blank=True, max_length=50)),
                ('twitter_link', models.CharField(blank=True, max_length=50)),
                ('instagram_link', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
