# Generated by Django 3.2.6 on 2021-08-31 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='created_at',
            new_name='joined_at',
        ),
    ]
