# Generated by Django 3.2.6 on 2021-08-31 16:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_created_at_trainer_joined_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('starting_time', models.TimeField()),
                ('ending_time', models.TimeField()),
                ('cover_image', models.ImageField(upload_to='dbImage/schedule')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.trainer')),
            ],
        ),
    ]
