# Generated by Django 3.2.6 on 2021-09-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage_title', models.CharField(blank=True, max_length=100)),
                ('advantage_desc', models.TextField(blank=True, max_length=500)),
                ('advantage_icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='intro',
            name='advantage_1_desc',
        ),
        migrations.RemoveField(
            model_name='intro',
            name='advantage_1_icon',
        ),
        migrations.RemoveField(
            model_name='intro',
            name='advantage_1_title',
        ),
        migrations.RemoveField(
            model_name='intro',
            name='tags',
        ),
    ]
