# Generated by Django 3.2.6 on 2021-09-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210901_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='is_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intro',
            name='is_display',
            field=models.BooleanField(default=False),
        ),
    ]
