# Generated by Django 3.2.6 on 2021-09-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210901_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advantage',
            old_name='advantage_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='advantage',
            old_name='advantage_icon',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='advantage',
            old_name='advantage_title',
            new_name='title',
        ),
    ]
